FROM php:8.0-apache

# Instala a extensão mysqli e outras dependências
RUN docker-php-ext-install mysqli pdo_mysql && docker-php-ext-enable mysqli pdo_mysql

# Atualiza o sistema, instala bibliotecas necessárias, e limpa o cache
RUN apt-get update && apt-get upgrade -y \
    && apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd \
    && apt-get clean && rm -rf /var/lib/apt/lists/*