version: '3.8'
services:
  php_apache_environment:
    container_name: php-apache
    build:
        context: ./php
        dockerfile: Dockerfile
    depends_on:
        - db  
    image: php:8.0-apache
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - 8016:80
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
        MYSQL_DATABASE: TRABALHO_ALEX
        MYSQL_USER: MYSQL_USER
        MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
        - "9906:3306"
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
          - '8006:80'
      restart: always
      environment:
          PMA_HOST: db
      depends_on:
          - db